ChuaDeThiMau/Models/ErrorViewModel.cs
namespace ChuaDeThiMau.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ChuaDeThiMau/Models/NhanVien.cs
namespace ChuaDeThiMau.Models;

public class NhanVien
{
    public Guid Id { get; set; }
    public string Ten { get; set; }
    public int Tuoi { get; set; }
    public int Role { get; set; }
    public string Email { get; set; }
    public int Luong { get; set; }
    public bool TrangThai { get; set; }
}

ChuaDeThiMau/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ChuaDeThiMau.Models;

namespace ChuaDeThiMau.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

ChuaDeThiMau/Controllers/NhanvienController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ChuaDeThiMau.Context;
using ChuaDeThiMau.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace ChuaDeThiMau.Controllers
{
    public class NhanvienController : Controller
    {
        private readonly MyDbContext _dbContext;

        public NhanvienController(MyDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        
        [HttpGet]
        public IActionResult Index()
        {
            var products = _dbContext.NhanViens.ToList();
            return View(products);
        }
        
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Create(NhanVien nhanVien)
        {
            _dbContext.Add(nhanVien);
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
        
        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            var nhanvien = _dbContext.NhanViens.Find(id);
            return View(nhanvien);
        }
        
        [HttpPost]
        public IActionResult Edit(NhanVien nhanVien)
        {
            var currentNhanVien = _dbContext.NhanViens.AsNoTracking().FirstOrDefault(nv => nv.Id == nhanVien.Id);
            var oldNhanVienJSON = JsonConvert.SerializeObject(currentNhanVien);
            HttpContext.Session.SetString("oldNhanVienJSON", oldNhanVienJSON);
            
            _dbContext.Update(nhanVien);
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
        
        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            var nhanvien = _dbContext.NhanViens.Find(id);
            _dbContext.Remove(nhanvien);
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
        
        [HttpPost]
        public IActionResult Rollback(Guid id)
        {
            var oldNhanVienJSON = HttpContext.Session.GetString("oldNhanVienJSON");
            if (oldNhanVienJSON != null)
            {
                var oldNhanVien = JsonConvert.DeserializeObject<NhanVien>(oldNhanVienJSON);
            
                _dbContext.Update(oldNhanVien);
                _dbContext.SaveChanges();
            }
            
            return RedirectToAction("Index");
        }
    }
}

ChuaDeThiMau/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ChuaDeThiMau/Views/Nhanvien/Create.cshtml
@model NhanVien

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<form asp-controller="Nhanvien" asp-action="Create" method="post">
    <div class="form-group">
        <label asp-for="Ten">Tên: </label>
        <input asp-for="Ten">
    </div>
    <div class="form-group">
        <label asp-for="Tuoi">Tuổi: </label>
        <input asp-for="Tuoi">
    </div>
    <div class="form-group">
        <label asp-for="Role">Role: </label>
        <input asp-for="Role">
    </div>
    <div class="form-group">
        <label asp-for="Email">Email: </label>
        <input asp-for="Email">
    </div>
    <div class="form-group">
        <label asp-for="Luong">Lương: </label>
        <input asp-for="Luong">
    </div>
    <div class="form-group">
            <label asp-for="TrangThai">Trạng Thái: </label>
            <input asp-for="TrangThai">
        </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

ChuaDeThiMau/Views/Nhanvien/Edit.cshtml
@model NhanVien

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<form asp-controller="Nhanvien" asp-action="Edit" method="post">
    <div class="form-group">
        <label asp-for="Ten">Tên: </label>
        <input asp-for="Ten" value="@Model.Ten">
    </div>
    <div class="form-group">
        <label asp-for="Tuoi">Tuổi: </label>
        <input asp-for="Tuoi" value="@Model.Tuoi">
    </div>
    <div class="form-group">
        <label asp-for="Role">Role: </label>
        <input asp-for="Role" value="@Model.Role">
    </div>
    <div class="form-group">
        <label asp-for="Email">Email: </label>
        <input asp-for="Email" value="@Model.Email">
    </div>
    <div class="form-group">
        <label asp-for="Luong">Lương: </label>
        <input asp-for="Luong" value="@Model.Luong">
    </div>
    <div class="form-group">
            <label asp-for="TrangThai">Trạng Thái: </label>
            <input asp-for="TrangThai">
        </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

ChuaDeThiMau/Views/Nhanvien/Index.cshtml
@model List<NhanVien>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<a class="btn btn-success" asp-controller="Nhanvien" asp-action="Create">Create New</a>
<table class="table">
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">Tên</th>
        <th scope="col">Tuổi</th>
        <th scope="col">Role</th>
        <th scope="col">Email</th>
        <th scope="col">Lương</th>
        <th scope="col">Trạng Thái</th>
        <th scope="col">#</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var nhanvien in @Model)
    {
        <tr>
            <th scope="row">@nhanvien.Id</th>
            <td>@nhanvien.Ten</td>
            <td>@nhanvien.Tuoi</td>
            <td>@nhanvien.Role</td>
            <td>@nhanvien.Email</td>
            <td>@nhanvien.Luong</td>
            <td>@nhanvien.TrangThai</td>
            <td>
                <a type="button" class="btn btn-primary" asp-controller="Nhanvien" asp-action="Edit" asp-route-id="@nhanvien.Id">Edit</a>
                <form asp-controller="Nhanvien" asp-action="Delete" asp-route-id="@nhanvien.Id" method="post">
                    <button type="submit" class="btn btn-danger" >Delete</button>
                </form>
                <form asp-controller="Nhanvien" asp-action="Rollback" asp-route-id="@nhanvien.Id" method="post">
                    <button type="submit" class="btn btn-warning" >Rollback</button>
                </form>
            </td>
        </tr>
    }
    </tbody>
</table>

ChuaDeThiMau/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - ChuaDeThiMau</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/ChuaDeThiMau.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ChuaDeThiMau</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - ChuaDeThiMau - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>